#pragma once
#include <cstdint>
#include <vector>

namespace nicolai {

struct LegacyWindowM36 {
    bool valid = false;
    int requested_length = 0;
    int lower_anchor = 0;
    int upper_anchor = 0;
    bool exact_anchor = false;
    std::vector<std::int16_t> q15;
};

// Static reconstruction of the direct cached domain used by 0x10109be0.
// The original cache is built by 0x1010a020 for lengths 20..400, while the
// direct pointer lookup covers requested lengths [20, 400). Anchor lengths are
// generated by repeated positive truncation of length*1.23 plus a final 400.
//
// This helper intentionally does not model the 0x10109be0 allocation/resampling
// fallbacks for requested lengths <20 or >=400 yet.
LegacyWindowM36 legacy_window_m36_direct(int requested_length);

std::vector<int> legacy_window_m36_anchors();

} // namespace nicolai
